language: go
sudo: false

go:
  - 1.13.3
  - tip

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - go test -v ./...

script:
  - $GOPATH/bin/goveralls -service=travis-pro

after_success:
  - bash <(curl -s https://codecov.io/bash)
