language: go

go:
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - tip

before_script:
  - go test -v ./...

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken aNGUU4KILuuMJa12HE39ltKOwFl46cnpl

after_success:
  - bash <(curl -s https://codecov.io/bash)
