language: go
sudo: false

go:
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

before_script:
  - go test -v ./...

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken aNGUU4KILuuMJa12HE39ltKOwFl46cnpl

after_success:
  - bash <(curl -s https://codecov.io/bash)
